name: eto_ride
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.2.15
  get: ^4.7.2
  geolocator: ^13.0.2
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  firebase_core: ^3.12.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  path_provider: ^2.1.5
  freezed_annotation: ^3.0.0
  injectable: ^2.5.0
  shared_preferences: ^2.5.2
  google_maps_flutter: ^2.10.1
  dashed_circle: ^0.0.2


dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFEB3B"                 # Background color (yellow)
  image: assets/images/splash.png # Path to your splash image
  android_12:
    image: assets/images/splash.png # Path to your splash image
  android: true                   # Enable Android splash
  ios: true                       # Enable iOS splash
  web: false                      # Disable web splash
  android_gravity: center         # Center the logo on Android
  ios_content_mode: center        # Center the logo on iOS
  fullscreen: true                # Use fullscreen for the splash screen

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Baloo_2
      fonts:
        - asset: font/baloo_2/Baloo2-Regular.ttf
        - asset: font/baloo_2/Baloo2-Medium.ttf

